#!/usr/bin/env python3
"""Generate src/macro/macro_wavetable.h for the Plaits mode's WAVETABLE engine from Plaits' own data
(github.com/pichenettes/eurorack, MIT): all 192 integrated waves (128 + 4 guard samples each) and the 64-wave
map of the fourth bank, which wavetable_engine.cc builds without user data as (192 + i) x 101 % 192.

    python3 tools/gen_wavetable_tables.py path/to/eurorack
"""
import re, sys, pathlib
er = pathlib.Path(sys.argv[1])
res = (er / "plaits" / "resources.cc").read_text()
m = re.search(r"const int16_t wav_integrated_waves\[\] = \{(.*?)\};", res, re.S)
waves = [int(v) for v in re.findall(r"-?\d+", m.group(1))]
assert len(waves) == 192 * 132, len(waves)
bank3 = [(192 + i) * 101 % 192 for i in range(64)]
out = ["/* Generated by tools/gen_wavetable_tables.py from Plaits (Emilie Gillet, MIT): do not edit. */",
       "#ifndef MACRO_WAVETABLE_H", "#define MACRO_WAVETABLE_H", "#include <stdint.h>", "",
       "/* wav_integrated_waves: 192 waves, 132 samples each */",
       "static const int16_t wt_waves[192 * 132] = {"]
for k in range(0, len(waves), 16):
    out.append("    " + ", ".join(str(v) for v in waves[k:k + 16]) + ",")
out += ["};", "", "/* the fourth bank's waves (LoadUserData without user data) */",
        "static const uint8_t wt_bank3[64] = {", "    " + ", ".join(str(v) for v in bank3), "};", "", "#endif", ""]
dst = pathlib.Path(__file__).resolve().parent.parent / "src" / "macro" / "macro_wavetable.h"
dst.write_text("\n".join(out))
print(f"wrote {dst}")
