#!/usr/bin/env python3
"""Writes engines/macro_dx7.h, the tables of the 6-OP (DX7) engine, from Plaits' sources (MIT):
the three factory banks (resources.cc syx_bank_0..2, 96 packed patches), lut_sine, and dx_units.cc's tables, in
the fixed-point formats macro.c uses; and the 32 algorithms as Plaits' Algorithms<6>::Compile() lays them out
(the render calls are dumped from Plaits itself by algdump.cc, compiled here).
    python3 tools/gen_dx7_tables.py path/to/eurorack"""
import pathlib, re, subprocess, sys, tempfile

ER = pathlib.Path(sys.argv[1] if len(sys.argv) > 1 else "../eurorack").resolve()
OUT = pathlib.Path(__file__).resolve().parent.parent / "macro_dx7.h"
res = (ER / "plaits" / "resources.cc").read_text()
dxu = (ER / "plaits" / "dsp" / "fm" / "dx_units.cc").read_text()


def floats(src, name):
    body = re.search(name + r"\[\w*\] = \{([^}]*)\}", src).group(1)
    return [float(v.strip().rstrip("f")) for v in body.replace("\n", " ").split(",") if v.strip()]


def ints(src, name):
    body = re.search(name + r"\[\] = \{([^}]*)\}", src).group(1)
    return [int(v, 0) for v in body.replace("\n", " ").split(",") if v.strip()]


def rows(v, per, fmt=str):
    return "\n".join("    " + ", ".join(fmt(x) for x in v[i:i + per]) + "," for i in range(0, len(v), per))


banks = []
for b in range(3):
    d = ints(res, "syx_bank_%d" % b)
    assert len(d) == 4096
    banks += d
sine = floats(res, "lut_sine")[:513]
coarse = floats(dxu, "lut_coarse")
ams = floats(dxu, "lut_amp_mod_sensitivity")
pms = floats(dxu, "lut_pitch_mod_sensitivity")
cube = floats(dxu, "lut_cube_root")
# NormalizeVelocity(0.8): 16 (Interpolate(lut_cube_root, 0.8, 16) - 0.918)
i, f = 12, 0.8 * 16 - 12
nvel = 16.0 * (cube[i] + (cube[i + 1] - cube[i]) * f - 0.918)

dump = r'''
#define private public
#include <cstdio>
#include "plaits/dsp/fm/algorithms.h"
using namespace plaits::fm;
int main() {
  static Algorithms<6> a; a.Init();
  for (int alg = 0; alg < 32; alg++) {
    int k = 0;
    for (int i = 0; i < 6; ) {
      const Algorithms<6>::RenderCall& c = a.render_call(alg, i);
      int src = -9, add = -1;
      for (const Algorithms<6>::RendererSpecs* r = Algorithms<6>::renderers_; r->n; ++r)
        if (r->render_fn == c.render_fn && r->n == c.n) { src = r->modulation_source; add = r->additive; break; }
      printf("%d %d %d %d %d %d\n", i, c.n, src, add, c.input_index, c.output_index);
      i += c.n; k++;
    }
    int m = 0;
    for (int i = 0; i < 6; i++) m |= a.is_modulator(alg, i) ? 1 << i : 0;
    printf("end %d\n", m);
  }
}
'''
with tempfile.TemporaryDirectory() as d:
    (pathlib.Path(d) / "algdump.cc").write_text(dump)
    subprocess.run(["c++", "-O1", "-w", "-I", str(ER), str(pathlib.Path(d) / "algdump.cc"),
                    str(ER / "plaits/dsp/fm/algorithms.cc"), str(ER / "plaits/resources.cc"), "-o", str(pathlib.Path(d) / "a")],
                   check=True)
    lines = subprocess.run([str(pathlib.Path(d) / "a")], capture_output=True, text=True, check=True).stdout.split("\n")
algs, mods, cur = [], [], []
for l in lines:
    if l.startswith("end"):
        algs.append(cur + [(-1, 0, 0, 0, 0, 0)] * (6 - len(cur)))
        mods.append(int(l.split()[1]))
        cur = []
    elif l.strip():
        i_, n, src, add, inp, outp = map(int, l.split())
        assert src != -9 and n in (1, 2, 3)
        cur.append((i_, n, src, add, inp, outp))
assert len(algs) == 32

out = f'''/* Generated by tools/gen_dx7_tables.py from Plaits (Emilie Gillet, MIT): the 6-OP engine's tables. */
#ifndef MACRO_DX7_H
#define MACRO_DX7_H

/* the three factory banks (resources.cc syx_bank_0..2): 96 DX7 patches, packed (128 bytes each) */
static const uint8_t dx7_patches[96 * 128] = {{
{rows(banks, 24, str)}
}};

/* lut_sine[0..512], Q30 */
static const int32_t dx7_sine[513] = {{
{rows([round(x * 2**30) for x in sine], 8)}
}};

/* lut_coarse: the ratio of each coarse setting in semitones, Q16 */
static const int32_t dx7_coarse[32] = {{
{rows([round(x * 65536) for x in coarse], 8)}
}};

/* lut_amp_mod_sensitivity (Q30), lut_pitch_mod_sensitivity (Q29: up to 2) */
static const int32_t dx7_ams[4] = {{ {", ".join(str(round(x * 2**30)) for x in ams)} }};
static const int32_t dx7_pms[8] = {{ {", ".join(str(round(x * 2**29)) for x in pms)} }};

/* NormalizeVelocity(0.8), the accent Plaits' voice gives an unpatched LEVEL, Q16 */
#define DX7_NVEL {round(nvel * 65536)}

/* Algorithms<6>::Compile(): per algorithm, the render calls (first operator, how many in a row, modulation source:
 * 0.. feedback from that one, -1 none, -2 the input buffer; additive; input and output buffer), then the modulators */
struct dx7_call {{ int8_t op, n, src, add, in, out; }};
static const struct dx7_call dx7_algs[32][6] = {{
''' + "\n".join("    {" + ", ".join("{%d, %d, %d, %d, %d, %d}" % c for c in a) + "}," for a in algs) + f'''
}};
static const uint8_t dx7_modulators[32] = {{ {", ".join(str(m) for m in mods)} }};

#endif
'''
OUT.write_text(out)
print("wrote", OUT, len(out), "bytes; normalized velocity", nvel)
