#!/usr/bin/env python3
"""Generate src/macro/macro_chord_tables.h for the Plaits mode's CHORD engine from Plaits' own data
(github.com/pichenettes/eurorack, MIT): the 15 integrated waves chord_engine.cc plays, its chord intervals as
Q16 ratios through stmlib's SemitonesToRatio tables, and its registrations as Q15.

    python3 tools/gen_chord_tables.py path/to/eurorack
"""
import re, struct, sys, pathlib

def f32(x):
    return struct.unpack("f", struct.pack("f", x))[0]

def array(src, name):
    m = re.search(r"const (?:float|int16_t) %s\[\] = \{(.*?)\};" % name, src, re.S)
    return [float(v.rstrip("f")) for v in re.findall(r"-?[0-9.e+-]+f?", m.group(1))]

er = pathlib.Path(sys.argv[1])
res = (er / "plaits" / "resources.cc").read_text()
units = (er / "stmlib" / "dsp" / "units.cc").read_text()
waves = [int(v) for v in array(res, "wav_integrated_waves")]
hi, lo = array(units, "lut_pitch_ratio_high"), array(units, "lut_pitch_ratio_low")

def semitones_to_ratio(s):                         # stmlib/dsp/units.h, in float32
    p = f32(f32(s) + 128.0)
    i = int(p)
    fr = f32(p - i)
    return f32(f32(hi[i]) * f32(lo[int(f32(fr * 256.0))]))

CHORDS = [(0.00, 0.01, 11.99, 12.00), (0.00, 7.00, 7.01, 12.00), (0.00, 5.00, 7.00, 12.00),
          (0.00, 3.00, 7.00, 12.00), (0.00, 3.00, 7.00, 10.00), (0.00, 3.00, 10.00, 14.00),
          (0.00, 3.00, 10.00, 17.00), (0.00, 2.00, 9.00, 16.00), (0.00, 4.00, 11.00, 14.00),
          (0.00, 4.00, 7.00, 11.00), (0.00, 4.00, 7.00, 12.00)]           # chord_bank.cc, not JON_CHORDS
NAMES = ["OCT", "5", "sus4", "m", "m7", "m9", "m11", "69", "M9", "M7", "M"]
REG = [(0.0, 1.0, 0.0, 0.0, 0.0, 0.0), (1.0, 0.0, 0.0, 0.0, 0.0, 0.0), (0.5, 0.0, 0.5, 0.0, 0.0, 0.0),
       (0.33, 0.0, 0.33, 0.0, 0.33, 0.0), (0.33, 0.0, 0.0, 0.33, 0.0, 0.33), (0.5, 0.0, 0.0, 0.0, 0.0, 0.5),
       (0.0, 0.5, 0.0, 0.0, 0.0, 0.5), (0.0, 0.1, 0.1, 0.0, 0.2, 0.6)]   # chord_engine.cc registrations
WAVES = [(2, 6, 1), (2, 6, 6), (2, 6, 4), (0, 6, 0), (0, 6, 1), (0, 6, 2), (0, 6, 7), (2, 4, 7), (2, 4, 6),
         (2, 4, 5), (2, 4, 4), (2, 4, 3), (2, 4, 2), (2, 4, 1), (2, 4, 0)]  # chord_engine.cc wavetable[]

out = ["/* Generated by tools/gen_chord_tables.py from Plaits (Emilie Gillet, MIT): do not edit. */",
       "#ifndef MACRO_CHORD_TABLES_H", "#define MACRO_CHORD_TABLES_H", "#include <stdint.h>", "",
       "#define CHORD_N 11", "/* chord_bank.cc's chords, SemitonesToRatio(), Q30 */",
       "static const uint32_t chord_ratio[CHORD_N][4] = {"]
for c, n in zip(CHORDS, NAMES):
    out.append("    {" + ", ".join("%du" % int(round(semitones_to_ratio(s) * 2 ** 30)) for s in c) + "},  /* %s */" % n)
out += ["};", "", "/* chord_engine.cc's registrations, Q15 */", "static const int16_t chord_reg[8][6] = {"]
for r in REG:
    out.append("    {" + ", ".join(str(int(round(f32(v) * 32768)) if v < 1 else 32767) for v in r) + "},")
out += ["};", "", "/* the 15 integrated waves chord_engine.cc plays, 132 samples each (128 + 4 guard) */",
        "static const int16_t chord_wave[15][132] = {"]
for b, r, c in WAVES:
    o = (b * 64 + r * 8 + c) * 132
    w = waves[o:o + 132]
    out.append("    {" + ", ".join(str(v) for v in w) + "},")
out += ["};", "", "#endif", ""]
dst = pathlib.Path(__file__).resolve().parent.parent / "src" / "macro" / "macro_chord_tables.h"
dst.write_text("\n".join(out))
print(f"wrote {dst}")
